US74173: Update ECS deploy file to allow for Fargate deployment
RepublicServicesRepository/ecs-deploy pull request #3
Opened 2022-06-29 17:20 UTC by murphry

2022-06-29 20:21 UTC, davidjameshowell approved these changes
LGTM. Only note is that this is **not** backwards compatible with EC2 deployments of ECS services.

2022-06-30 23:14 UTC, nickdemarco89 approved these changes

2022-06-30 23:37 UTC, davidjameshowell approved these changes

2022-07-01 00:23 UTC, akaustav approved these changes
One comment.

2022-07-01 00:23 UTC, akaustav commented on Dockerfile
> +# RUN    pip install awscli
Consider removing this commented line if it is not necessary.

```suggestion
```

2022-07-01 00:24 UTC, davidjameshowell requested changes
Just saw, we still need the AWS CLI command still @murphry

2022-07-05 16:21 UTC, KHannel commented on Dockerfile
> +RUN    pip install awscli
should these be combined into a single RUN?

2022-07-05 16:40 UTC, merged